<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'breed'                                      => '',
    'Address'                                    => 'Адрес',
    'Birth Country'                              => 'Страна рождения',
    'Birth Economy'                              => 'Хозяйство рождения',
    'Birth Year'                                 => 'Год рождения',
    'Birthday'                                   => 'Дата рождения',
    'Body'                                       => 'Корпус',
    'Breast Girth'                               => 'Обхват груди',
    'Breed'                                      => 'Порода',
    'Breed'                                      => 'Порода',
    'Breeds'                                     => 'Породы',
    'Chip Number'                                => 'Номер чипа',
    'Colour'                                     => 'Масть',
    'Comments'                                   => 'Комментарии',
    'Create'                                     => 'Добавить',
    'Add Breed'                                  => 'Добавить Породу',
    'Add Description'                            => 'Добавить Описание',
    'Add Horse'                                  => 'Добавить Лошадь',
    'Add Owner'                                  => 'Добавить Владельца',
    'Add Passport'                               => 'Добавить Паспорт',
    'Add Promers'                                => 'Добавить Промеры',
    'Add Results'                                => 'Добавить Результат',
    'Add Vaccination'                            => 'Добавить Вакцинацию',
    'Add Working Capacity'                       => 'Добавить Сведения о работоспособности',
    'Date'                                       => 'Дата',
    'Delete'                                     => 'Удалить',
    'Descriptions'                               => 'Описание',
    'Doctor'                                     => 'Ф.И.О. ветврача',
    'External Signs'                             => 'Внешние признаки',
    'Father'                                     => 'Отец',
    'Gpk'                                        => 'Запись в ГПК',
    'Head'                                       => 'Голова',
    'Height'                                     => 'Высота в холке',
    'Hippodrome'                                 => 'Ипподром',
    'Horse'                                      => 'Кличка',
    'Horses'                                     => 'Лошади',
    'I'                                          => 'I',
    'ID'                                         => 'Номер',
    'Ii'                                         => 'II',
    'Iii'                                        => 'III',
    'Jockey'                                     => 'Жокей',
    'Left Back'                                  => 'Левая задняя',
    'Left Front'                                 => 'Левая передняя',
    'Male'                                       => 'Мальчик',
    'Female'                                     => 'Девочка',
    'Mother'                                     => 'Мать',
    'Mouth Grasp'                                => 'Обхват Пясти',
    'Name'                                       => 'Кличка',
    'Neck'                                       => 'Шея',
    'Organization'                               => 'Организация',
    'Owner'                                      => 'Владелец',
    'Owner'                                      => 'Владелец',
    'Owners'                                     => 'Владельцы',
    'Packing Number'                             => 'Номер упаковки',
    'Passport Number'                            => 'Номер паспорта',
    'Passports'                                  => 'Паспорта',
    'Place'                                      => 'Место',
    'Prize'                                      => 'Приз',
    'Promers'                                    => 'Промеры',
    'Rating'                                     => 'Рейтинг',
    'Registration Number'                        => 'Регистрационный номер',
    'Reset'                                      => 'Сбросить',
    'Results'                                    => 'Результаты',
    'Right Back'                                 => 'Правая задняя',
    'Right Front'                                => 'Правая передняя',
    'Sale Date'                                  => 'Дата продажи',
    'Search'                                     => 'Поиск',
    'Sex'                                        => 'Пол',
    'Slanting Length'                            => 'Косая длина',
    'Starts'                                     => 'Старты',
    'Title'                                      => 'Название',
    'Update'                                     => 'Обновить',
    'Update {modelClass}: '                      => 'Обновить:',
    'Vaccinations'                               => 'Вакцинации',
    'Verification Date'                          => 'Дата описания',
    'Weight'                                     => 'Вес',
    'Win'                                        => 'Выйгрыш',
    'Working Capacities'                         => 'Сведения о работоспособности',
    'Username'                                   => 'Имя пользователя',
    'Password'                                   => 'Пароль',
    'RememberMe'                                 => 'Запомнить меня',
];
