<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Horses App'                                 => 'Horses CRUD App',
    'Adress'                                     => '',
    'Are you sure you want to delete this item?' => '',
    'Birth Country'                              => '',
    'Birth Economy'                              => '',
    'Birth Year'                                 => '',
    'Birthday'                                   => '',
    'Body'                                       => '',
    'Breast Girth'                               => '',
    'Breed'                                      => '',
    'Breeds'                                     => '',
    'Chip Number'                                => '',
    'Colour'                                     => '',
    'Comments'                                   => '',
    'Create'                                     => '',
    'Add Breed'                                  => '',
    'Add Description'                            => '',
    'Add Horse'                                  => '',
    'Add Owner'                                  => '',
    'Add Passport'                               => '',
    'Add Promer'                                 => '',
    'Add Results'                                => '',
    'Add Vaccination'                            => '',
    'Add Working Capacity'                       => '',
    'Date'                                       => '',
    'Delete'                                     => '',
    'Descriptions'                               => '',
    'Doctor'                                     => '',
    'External Signs'                             => '',
    'Father'                                     => '',
    'Gpk'                                        => '',
    'Head'                                       => '',
    'Height'                                     => '',
    'Hippodrome'                                 => '',
    'Horse'                                      => '',
    'Horses'                                     => '',
    'I'                                          => '',
    'ID'                                         => '',
    'II'                                         => '',
    'III'                                        => '',
    'Jockey'                                     => '',
    'Left Back'                                  => '',
    'Left Front'                                 => '',
    'Mother'                                     => '',
    'Mouth Grasp'                                => '',
    'Name'                                       => '',
    'Neck'                                       => '',
    'Organization'                               => '',
    'Owner'                                      => '',
    'Owners'                                     => '',
    'Packing Number'                             => '',
    'Passport Number'                            => '',
    'Passports'                                  => '',
    'Place'                                      => '',
    'Prize'                                      => '',
    'Promers'                                    => '',
    'Rating'                                     => '',
    'Registration Number'                        => '',
    'Reset'                                      => '',
    'Results'                                    => '',
    'Right Back'                                 => '',
    'Right Front'                                => '',
    'Sale Date'                                  => '',
    'Search'                                     => '',
    'Sex'                                        => '',
    'Slanting Length'                            => '',
    'Starts'                                     => '',
    'Title'                                      => '',
    'Update'                                     => '',
    'Update {modelClass}: '                      => '',
    'Vaccinations'                               => '',
    'Verification Date'                          => '',
    'Weight'                                     => '',
    'Win'                                        => '',
    'Working Capacities'                         => '',
    'breed'                                      => '',
];
